### ISSUE TITLE
Events not going through the routes under load

### ISSUE THREAD

**Issue by holidaymike** [xmidt-org/ears#161]
Running perf test with 6000 events at 100 events/sec in Ears QA, we see that only ~5500 events get through the routes when the expectation is all 6k events go through. Need to investigate

**Comment by boriwo** [comment]
Root cause is that the dynamo db persistence layer converts empty arrays to null so 

```
{
      "plugin": "match",
      "name": "accountProductRouteEmptyMatcher",
      "config": {
        "mode": "deny",
        "matcher": "pattern",
        "pattern": {
          "message": {
            "payload" : {
              "body" : {
                "addedAccountProducts" : [],
                "removedAccountProducts": []
              }
            }
          }
        }
      }
    },
```

becomes 

```
 {
      "plugin": "match",
      "name": "accountProductRouteEmptyMatcher",
      "config": {
        "mode": "deny",
        "matcher": "pattern",
        "pattern": {
          "message": {
            "payload" : {
              "body" : {
                "addedAccountProducts" : null,
                "removedAccountProducts": null
              }
            }
          }
        }
      }
    },
```

Therefore there is a hash inconsistency between the live route and the stored route and the global table syncer will update and restart the route (persistence layer is considered the source of truth).

At this point a second bug kicks in which results in 60 seconds passing between shutting the original route and restarting the modified one. Hence, during a long running test we lose about 60 sec worth of events for routes that contain empty arrays in their configs (in this particular test only the accountProductRoute is affected).

Verified fixes for these bugs are here

https://github.com/xmidt-org/ears/commit/72d6a449ed7c561836082a48b9d347d5da9f1b64

https://github.com/xmidt-org/ears/commit/97fe08b2f47dff315cdec7670c41341a3b7c9cc0
