### ISSUE TITLE
Context propagation and cancelling

### ISSUE THREAD

**Issue by gtrevg** [xmidt-org/ears#51]
We follow a standard of passing in a `ctx context.Context` into our functions so that:

* The transaction can be cancelled
* The context can be used for tracing/metrics

For long running contexts (such as `receiver.Receive`) as well as context that may need to be shared among several receivers, we need to figure out the best approach for managing those contexts when it comes to cancelling and metrics.  After some of the dust settles, we should spend some time mapping the context object throughout the system to ensure we're on the same page for how it behaves and how we've implemented it across the system.

**Comment by gtrevg** [comment]
Discussion note:
* When ears cli starts up, it will create something like `appCtx := context.Background()`
* For UberFX initialization, this `appCtx` will be passed in
* All components can create sub-contexts off of this
* The expectation is that this context will continue to run until the app is shut down.

**Comment by gtrevg** [comment]
Discussion notes:

Possibly 3 contexts:
* Initialization context (`ProvideInitializationContext`)
  * Resources link off of this for initialization processes
  * Can also be used to cancel the initialization process
* Runtime context
  * Used for runtime lifecycle management
  * Cancelling of long running processes (Like RoutingManager)
* Event Context
  * When an event is being processed, we want a new context for this path
  * This gives us visibility into how an event comes in and how it impacts the routing and other external systems
  * Gives us good metrics on end-to-end transaction time as we can look at the total time for that one particular trace

**Comment by holidaymike** [comment]
Here are my investigation and thoughts:

There are (at least?) 3 types of context that EARS should handle:
- API request contexts
- Receiver event contexts
- Uberfx start and stop contexts

I think we don't need global/runtime context (more on this later).

### API Request context
Every golang http request already comes with a context. For request scoped logging, EARS current create a [subcontext](https://github.com/xmidt-org/ears/blob/main/internal/pkg/app/middlewares.go#L38) and pass it downstream with the request. I would assume that we can handle metric/tracing in similar fashion. 

As we process the API request context, we have the option to monitor the context done channel for cancellation. This allows us to cancel downstream network/IO operation such as [dynamodb access](https://github.com/xmidt-org/ears/blob/routingmgr/internal/pkg/db/dynamo/dynamodb_storer.go#L147)

Also, the request context pattern might be useful for us in the Receiver event context. I am listing some methods here
that will facilitate our discussion later in event context:
```go
func NewRequestWithContext(ctx context.Context, method, url string, body io.Reader) (*Request, error) 
func (r *Request) Context() context.Context
func (r *Request) Clone(ctx context.Context) *Request
func (r *Request) WithContext(ctx context.Context) *Request
```

### Receiver event context
Receiver event context is very similar to API request context:
- Enable event scoped logging (and metric/tracing in the future)
- Allow downstream network/IO cancellation (most likely in Sender)

When a Receiver generates an event, it should call one of the following event constructors:
```go
func NewEvent(payload interface{}) (Event, error)
func NewEventWithContext(ctx context.Context, payload interface{}) (Event, error)
```

The first constructor will create a new Background context with the event. The second constructor allows Receiver to provide its own context (for example, to timeout an event after 10 seconds)

The event interface should have an accessor to retrieve the context
```go
Context() context
```

There should be a way to duplicate event with a new context (Clone vs WithContext)
```go
Clone(ctx context.Context) Event
WithContext(ctx context.Context) Event
```

A couple of things to note at this point:
- Similar to the way a request comes in and EARS middleware create a subcontext, EARS will need to create subcontexts for event context after Receiver calls the next function.
- Because event now contains a context, we do not need context as a parameter as we pass events downstream

Here is an example on how the [next function](https://github.com/xmidt-org/ears/blob/main/internal/pkg/plugin/manager.go#L224-L232) can handle the creation of the subcontexts:
```go
    for _, n := range nextFns {
        wg.Add(1)
        go func(fn pkgreceiver.NextFn) {
            ctx := e.Context()
            
            //create sub-context for each route
            subCtx := SubLoggerCtx(ctx, logger)
            StrToLogCtx(subCtx, "traceId", uuid.NewId())

            err := fn(e.WithContext(subCtx))
            if err != nil {
                errCh <- err
            }
        }(n)
    }
```

There are two existing helper functions in the example above:
```go
//Create a sub-context given a parent context and a zerolog logger
SubLoggerCtx(ctx, logger)

//Append log key/value pair to a sub-context
StrToLogCtx(subCtx, logKey, logValue)
```

For context specific logging, we can simply use zerolog `Ctx` function:
```go
log.Ctx(subCtx).Info().Msg("some log")
```

There is an open issue to the approach above:
- How do we enable Receiver to inject logging/tracing information? Do we expose a set of help functions like the ones above so that Receivers can manipulate the context

### Uberfx start and stop contexts
Uberfx provides two contexts, one for app initialization and one for app termination. They have the following signature:

```go
	lifecycle.Append(
		fx.Hook{
			OnStart: func(context.Context) error {
		        //Startup code
			},
			OnStop: func(ctx context.Context) error {
				//Termination code
			},
		},
	)
```

The startup context is a 15-second timeout (configurable) context, and stop context is a 20-second? timeout context. These contexts are for transactions during startup/stop. They do not have meaning while the application is running. For EARS, they should mainly be used for cancelling network/IO initialization (for example, initialize a connection to a DB).

### What about Global/Runtime context?
We don't need it. 
- For logging, there is already a global logger which we provide through `ProvideLogger`. 
- For application life-cycle, uberfx is managing the application lifecycle for us. Our high-level constructs like routing manager or plugin manager should have its own start/stop functions that the lifecycle hooks can call into. They do not need to listen to a global context `Done` channel for shutdown events.

Some receivers may <strong>choose</strong> to have its own context for stopping its network/IO when it is shutdowning down. This is really Receiver dependent and is really optional.
